### ISSUE TITLE
CSS 系列 - 移动端小技巧

### ISSUE THREAD

**Issue by BlackCubeNo99** [BlackCubeNo99/Blog#40]
## 格式化银行卡号

```js
let str = '1234567890123456789099'
str.replace(/[0-9](?=([0-9]{4})+)/g, '*').replace(/(?!^)(?=([0-9*]{4})+$)/g, ' ')
```

## SVG 帧动画 - 避免 rem 帧动画抖动

```html
<div class="gather_guide">
    <svg viewBox="0, 0, 246, 450" class="gather_guide_anim">
        <image xlink:href="images/gather_share_anim.png" width="1476" height="450"></image>
    </svg>
</div>
```

```css
```css
.gather_guide {
    position: absolute;
    top: 0;;
    right: 0;;
    width: 100%;
    height: 100%;
    background-color: rgba(#000, .85);
    z-index: $index_mask;
    overflow: hidden;
    &_anim {
        position: absolute;
        top: 0;
        left: 50%;
        margin-left: rem(-48);
        width: rem(246);
        height: rem(450);
        image {
            animation: gather_guide_anim .5s steps(5) both;
        }
    }
}

@keyframes gather_guide_anim {
    100% {
        transform: translate3d(-1230px, 0, 0);
    }
}
```

## Date 日期计算返回 NAN Bug

Safari 浏览器的 `Date.parse()` 无法处理 YYYY-MM-DD HH:MM:SS 格式的日期

所以，在通过毫秒数计算时间差的时候要转成 YYYY/MM/DD HH:MM:SS 格式

```js
const date = Date.parse(nowDate.replace(/-/g), '/')
```

## 获取 url 参数

```js
function getUrlParam (name, url) {
    //参数：变量名，url为空则表从当前页面的url中取
    var u = arguments[1] || window.location.search,
        reg = new RegExp('(^|&)' + name + '=([^&]*)(&|$)', 'i'),
        r = u.substr(u.indexOf('\?') + 1).match(reg)  

    return r != null ? r[2] : ''
}
```

## 保留一位小数

```js
function digitOne(n) {
    var s = parseFloat(n).toFixed(2)
    return s.substring(0, s.indexOf('.') + 2)
}
```

## 立方体 3D

`transform-style` 保留子元素的 3D 效果，比如：

两个嵌套的元素，div1 和 div2 都做了 rotateY，如果不加的话，div2 会没有 rotateY 效果，看起来就像是纯粹的压扁了宽度。

```html
<div class="div1">
    <div class="div2"></div>
</div>
```

使用六张图片，通过 rotateX、rotateY 来进行拼接，拼成一个立体的六面体，将镜头置于六面体的中心，通过选装父元素的 rotateY 来实现预览。

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>六面矩形</title>
    <style>
        html,
        body {
            margin: 0;
            height: 100%;
            overflow: hidden;
        }

        .stage {
            perspective: 800px;
            /* 让子元素获得透视效果，及 3D 效果，当前元素效果不变化 */
            width: 1024px;
            height: 1024px;
            /* 设置画布居中 */
            position: absolute;
            top: 50%;
            left: 50%;
            margin: -512px 0 0 -512px;
        }

        .ctx {
            transform: translateZ(400px);
            transform-style: preserve-3d;
            /* 使被转换的子元素保留其 3D 转换，配合 perspective 使用 */
            animation: rotate360deg 20s linear infinite;
        }

        .face {
            position: absolute;
            top: 0;
            left: 0;
            width: 1024px;
            height: 1024px;
        }

        .top {
            /* 头顶 */
            background: url(images/top.jpg) no-repeat 0 0;
            transform: rotateX(-90deg) translateZ(-512px)
        }

        .bottom {
            /* 底部 */
            background: url(images/bottom.jpg) no-repeat 0 0;
            transform: rotateX(90deg) translateZ(-512px);
        }

        .after {
            /* 前面 */
            background: url(images/after.jpg) no-repeat 0 0;
            transform: translateZ(-512px);
        }

        .left {
            /* 左边 */
            background: url(images/left.jpg) no-repeat 0 0;
            transform: rotateY(90deg) translateZ(-512px);
        }

        .right {
            /* 右边 */
            background: url(images/right.jpg) no-repeat 0 0;
            transform: rotateY(90deg) translateZ(512px);
        }

        .first {
            /* 后面 */
            background: url(images/first.jpg) no-repeat 0 0;
            transform: translateZ(512px);
        }

        /*
			    	前
			顶	左	底	右（显示是背面的，所以原图要水平反转
      				后
        */


        @keyframes rotate360deg {
            0% {
                transform: translateZ(400px) rotateY(0deg);
            }

            50% {
                transform: translateZ(400px) rotateY(180deg);
            }

            100% {
                transform: translateZ(400px) rotateY(360deg);
            }
        }
    </style>
</head>

<body>
    <div class="stage">
        <div class="ctx">
            <div class="face top"></div>
            <div class="face bottom"></div>
            <div class="face after"></div>
            <div class="face left"></div>
            <div class="face right"></div>
            <div class="face first"></div>
        </div>
    </div>
</body>

</html>
```

## iOS 圆角渲染 Bug

在 iOS 中，在页面中使用了 JS 来切换 transform 动画时，页面中的某些元素的 border-radius 的发生抖动，圆角和非圆角的状态来回切换。

给元素添加 CSS 样式：

```css
.example {
    -webkit-mask-image: -webkit-radial-gradient(white, black);
}
```

## 限制 max-width 超出省略号错误

```sass
.example {
    padding: 0 5px;
    max-width: 120px;
    width: fit-content;
    box-sizing: border-box;
    @include line;
}
```

box-sizing 会影响 max-width 的判断，导致没达到最大宽度就出现省略号了

解决方案：不使用 box-sizing

## 微信自动播放音频

放最开头

```js
document.addEventListener('qbrowserVisibilityChange', function(e) {
    var evt = document.createElement('HTMLEvent')
    evt.initEvent('visibilitychange', false, false)
    evt.hidden = e.hidden
}, true)

document.addEventListener('visibilitychange', function(e) {
    e.hidden = e.hidden == undefined ? document.hidden : e.hidden
}, true)
```

然后，统一使用一个 visibilitychange 事件，当业务处理

```js
// 关闭音乐
document.addEventListener('visibilitychange', function(e) {
    if (audio.isMuted == true) return false
    e.hidden === true ? audio.pause() : audio.play() // 播放失败，可以尝试加个 setTimeout
})
```

## iOS 9.xx 旧版本布局渲染有问题

子元素有 `position: absolute`，父元素一定要加 `position: relative`。

## iOS 8.2 transition: transform .5s linear 无效

iOS 8.2 不支持，改为 `transition: all .5s linear`。

## 可变化高度的 textarea

不要使用 div 加 contenteditable 的方式模拟，虽然前端实现了，但开发似乎有些需求无法完成，使用 textarea 监听 input 事件。

```js
var release_con = document.querySelectorAll('.quan_release_con textarea')

for (var i = 0; i < release_con.length; i++) {
    release_con[i].addEventListener('input', function() {
        this.style.height = this.scrollHeight + 'px'
    }, false)
}
```

## iOS rem 布局渲染高度为 0

只发生在 iOS，初步定位是 rem 渲染出现错误，组内解决方案是，页面加载完成后，修改 html fontsize 的值，随后再改回来，触发 rem 的计算，重新渲染。

```js
if(navigator.userAgent.indexOf("iPhone") >= 0) {
    // 针对IOS的hack 
    var FONTSIZE = parseFloat(window.getComputedStyle(document.documentElement).fontSize)
    var doSomething = function() { 
        document.documentElement.style.fontSize = (FONTSIZE + 1) + 'px'
        setTimeout(function() {
            document.documentElement.style.fontSize = FONTSIZE + 'px' 
        }, 0)
    }
    'complete' == document.readyState ? doSomething() :  document.addEventListener('DOMContentLoaded', doSomething)
}
```

工作中常用的一些技巧，放在这里，没有特意归类，请随意。

## 使用 sticky 属性的情况下，父元素不能有 overflow : hidden

否则会导致 sticky 失效

## iOS rotate 360deg 动画，不要 0deg - 360deg

中间间隔 180deg

```css
@keyframes rotate {
    0% {
        transform: rotate(0deg);
    }
    50% {
        transform: rotate(180deg);
    }
    100% {
        transform: rotate(360deg);
    }
}
```

## transition 不要用 all

针对用到的缓动属性去定义，不要一股脑的 all，那样会带来一些不必要的麻烦（具体什么麻烦忘记了

## 插入音乐
```javascript
var url = 'images/song.mp3'
window.audio = document.createElement('audio')
var source = document.createElement('source')
audio.id = 'audio'
source.type = 'audio/mpeg'
source.src = url
source.autoplay = 'autoplay'
// 音乐循环
audio.addEventListener(
    'ended',
    function() {
        audio.play()
    },
    false
)

audio.appendChild(source)
audio.play()
```

## 计算两点的距离

```javascript
var x1 = eval(form.x1.value);
var y1 = eval(form.y1.value);
var x2 = eval(form.x2.value);
var y2 = eval(form.y2.value);
var xdiff = x2 - x1;
var ydiff = y2 - y1;
form.answer.value = Math.pow((xdiff * xdiff + ydiff * ydiff), 0.5);
```

## 宽高长图片自适应布局

```css
/* 判断图片宽高，分开处理 */
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
&.w {
  width: 100%;
  height: auto;
}
&.h {
  width: auto;
  height: 100%;
}
```

## iOS 下避免吸顶元素是输入框

这会导致在弹出输入框滑动屏幕时，吸顶元素会表现的像 absolute 导致错位，需要做一些额外的判断，可以参考网上各种实现方案。

## input 标签输入时光标不居中问题

解决方案是不要给 `<input>` 标签加 `line-height` 属性

反驳：不完美，对于 placeholder 属性的文字，并不居中。

## 设置 height 和 line-height 为相同值时，在 Android 无法垂直居中

```css
::before {
    content: '';
    display: inline-block;
    vertical-align: middle;
    width: 0;
    height: 100%;
    margin-top: 1px;
}
```

## 关于 Android 微信 X5 查某个属性支持度

iOS系统微信使用的是 Safari 的内核，查支持度到 Can I use 即可。

Android 则不同，还得看 X5 的脾气，所以以下是查支持度的步骤：

* 查[浏览器 UA](http://motool.github.io/ua/)
* 得知 TBS 版本号
    * QQ 浏览器：6.2 版本及以后使用 Blink 内核。
    * X5 tbs 1.x：版本号为 02xxxx，使用 Webkit 内核。
    * X5 tbs 2.x：版本号为 03xxxx。使用 Blink 内核。
    * X5 tbs 3.x：版本号为 04xxxx。使用 Blink 内核。
    * UA 包含 “TBS/0365xx” 字段即说明当前环境已升级到 TBS2.1 版本。
* 通过 [X5 Can I use](http://res.imtt.qq.com/tbs/incoming20160607/home.html) 查属性的支持度

## 修改 iPhone Safari 下 input disabled 的颜色

```css
input:disabled {
    -webkit-text-fill-color: #ddd;
}
```

## fit-content 不定宽元素居中

居中的两种旧方式：一是定宽度加 `margin: 0 auto`、二是外层 `text-align: center;` 里层 `display: inline-block;`

```html
<div class="more_btn">查看更多</div>
```
```css
.more_btn {
    margin: auto;
    padding: 0 30px;
    width: -webkit-fit-content;
    width: fit-content; /* 第三种方法 */
    height: 40px;
    line-height: 40px;
    background: #4caf50;
    color: #fff;
    font-size: 14px;
    text-align: center;
    border-radius: 4px;
}
```

[DEMO 点击这里](http://jsbin.com/vecupuruma/1/edit?html,css,output)

## appearance 取消默认样式

```css
/* 去掉date类型input的叉叉 */
::-webkit-clear-button {
    -webkit-appearance: none; 
}

/* 去掉number类型的上下箭头 */
::-webkit-inner-spin-button {
     -webkit-appearance: none;
}

/* 去除圆角 */
input[type=search] {
    -webkit-appearance: none;
}

/* 隐藏取消按钮 */
::-webkit-search-cancel-button {
    -webkit-appearance: none;
}

/* 隐藏放大镜 */
::-webkit-search-results-button {
    -webkit-appearance: none;
}
```

## SVG 实现环形进度条

参考资料：https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/Paths

## SVG 实现飘带文字

``` html
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
xmlns:xlink="http://www.w3.org/1999/xlink" viewbox="0, 0, 332, 48" width="400" height="300" style="border: 1px solid #000">
    <path id="textPath" d="m0.749997,39.860256c92.99817,20.99958 250.99507,-15.99969 327.99356,1.99996" opacity="0.5" stroke-opacity="null" stroke-width="1" stroke="none" fill="none"></path>
    <text fill="#000" font-size="28" x="0" y="0">
        <textPath xlink:href="#textPath" text-anchor="middle" startOffset="50%">
            利益点利益点利益点
        </textPath>
    </text>
</svg>
```

> `viewbox` 属性用于缩放，具体效果可参考：[理解SVG的viewport,viewBox,preserveAspectRatio](http://www.zhangxinxu.com/wordpress/2014/08/svg-viewport-viewbox-preserveaspectratio/)
> `<path>` 则是绘制文件的路径，可通过 Adobe AI 导出
> `<text>` 则是定义文本，`<textPath>` 绘制路径上的文字
> 当 `viewbox` 没有设置宽度时，根据上一层宽高进行缩放

[DEMO 点击这里](http://jsbin.com/bihowamoce/3/edit?html,output)

## 渐变文字与镂空文字

``` html
<p class="gradient_txt">渐变文字渐变文字渐变文字渐变文字</p>
<p class="hollow_txt">镂空文字镂空文字镂空文字镂空文字</p>  
```

``` css
.gradient_txt {
    background-color: #890ffa;
    background-image: gradient(linear, left top, right top, from(#890ffa), to(#d80078));
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.hollow_txt {
    font-size: 50px;
    -webkit-text-stroke: 1px #000;
    -webkit-text-fill-color: transparent;
}
```

> 镂空文字对较小的文字不友善，目前未有较好的办法

[DEMO 点击这里](http://jsbin.com/jiyudeyopu/1/edit?html,css,output)

## 去掉倒数几个元素

``` css
&:not(:nth-last-child(-n+4)) { // 除了倒数4个
    margin-bottom: 10px;
}
```

## 去掉最后一个元素的某个属性

> 比如给一列的`<li>`元素加 margin-bottom: 10px; 最后一个为 margin-bottom: 0;

``` css
/* 常规写法 */
li {
    width: 100px;
    height: 100px;
    margin-bottom: 10px;
}
li:last-child {
   margin-bottom: 0;
}
```

``` css
/* 推荐写法 */
li {
    width: 100px;
    height: 100px;
}
li:not(:last-child) {
   margin-bottom: 10px;
}
```

> 好处在于不需要覆盖原属性值达到效果

## iOS 视频内嵌，不全屏播放

``` html
<video webkit-playsinline src="video.mp4"></video>
```

> 关于 Android 内嵌视频目前仅在腾讯域名白名单下才能较好的运行
> 另外推荐 [iphone-inline-video](https://github.com/bfred-it/iphone-inline-video) 库，实现 iOS 内嵌视频并且隐藏 iOS 视频的播放暂停按钮

## 隐藏 iOS 视频的播放暂停按钮

``` css
video::-webkit-media-controls-play-button,
video::-webkit-media-controls-start-playback-button {
    opacity: 0;
    pointer-events: none;
    width: 5px;
}
```

## 判断浏览器是否支持 WebP

``` js
;(function() {
    var img = new Image()
    img.onload = function() {
        if (img.width > 0 && img.height > 0) {
            document.documentElement.className = 'webp'
            window.webpSupport = true
        }
    }
    img.onerror = function() {}
    img.src =
        'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA'
})()
```

## 判断浏览器是否支持 APNG

``` js
;(function() {
    'use strict'
    var apngTest = new Image(),
        ctx = document.createElement('canvas').getContext('2d')
    apngTest.onload = function() {
        ctx.drawImage(apngTest, 0, 0)
        self.apng_supported = ctx.getImageData(0, 0, 1, 1).data[3] === 0
    }
    apngTest.src =
        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACGFjVEwAAAABAAAAAcMq2TYAAAANSURBVAiZY2BgYPgPAAEEAQB9ssjfAAAAGmZjVEwAAAAAAAAAAQAAAAEAAAAAAAAAAAD6A+gBAbNU+2sAAAARZmRBVAAAAAEImWNgYGBgAAAABQAB6MzFdgAAAABJRU5ErkJggg=='
})()
```

> 不支持的浏览器则在 `getImageData(0, 0, 1, 1).data[3]` 获取 alpha 通道会返回 `[0, 0, 0, 255]`
> 支持的浏览器则返回 `[0, 0, 0, 0]`

## @supports 根据浏览器对 CSS3 特性的支持情况来定义不同样式

``` css
/* 当浏览器支持弹性布局，括号内的样式生效 */
@supports (display: flex) {
    .example {
        display: flex;
    }
}
```

``` css
/* 当浏览器不支持弹性布局，括号内的样式生效 */
@supports not (display: flex) {
    .example {
        float: left;
    }
}
```

``` css
/* 与或判断 */
@supports ((display: -webkit-flex) or 
    (display: -moz-flex) or
    (display: flex)) and (-webkit-appearance: caret) {
    /* use styles here */
}
```

``` javascript
// JavaScript中提供了 window.CSS.supports 方法
// 第一种方法
var supportsFlex = CSS.supports('display', 'flex')
// 第二种方法
var supportsFlexAndAppearance = CSS.supports('(display: flex) and (-webkit-appearance: caret)')
```

## 隐藏滚动条

``` css
.example::-webkit-scrollbar {
    width: 0;
    height:0;
    display: none;
}
```

## 弹性滚动

``` css
/* 目前仅支持 iOS */
.example {
    -webkit-overflow-scrolling: touch;
}
```

## 自定义滚动条

``` css
.example::-webkit-scrollbar { 
    width: 6px;
    height: 4px;
}
.example::-webkit-scrollbar-button {
    width: 0;
    height: 0;
}
.example::-webkit-scrollbar-corner {
    display: block;
}
.example::-webkit-scrollbar-thumb {
    background-clip: padding-box;
    background-color: #fff;
}
```

## CSS3 滤镜

``` css
.example-1 {
    -webkit-filter: blur(5px); /* 毛玻璃 */
}

.example-2 {
    -webkit-filter: grayscale(0.5); /* 灰度 */
}

.example-3 {
    -webkit-filter: sepia(0.5); /* 褐色 */
}

.example-4 {
    -webkit-filter: brightness(3); /* 亮度 */
}

.example-5 {
    -webkit-filter: hue-rotate(180deg); /* 色相 */
}

.example-6 {
    -webkit-filter: invert(1); /* 反色 */
}

.example-7 {
    -webkit-filter: opacity(0.5); /* 透明度 */
}

.example-8 {
    -webkit-filter: saturate(5); /* 饱和度 */
}

.example-9 {
    -webkit-filter: contrast(0.5); /* 对比度 */
}

.example-10 {
    -webkit-filter: drop-shadow(10px 10px 5px rgba(0, 0, 0, 0.9)); /* 阴影 */
}
```

[DEMO 点击这里](http://jsbin.com/vasiperusi/edit?html,css,output)

## 单行文字超出省略号

``` css
.example {
    width: 200px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-scaple: nowrap;
}
```

## 多行文字超出省略号

``` css
.example {
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2; /* 溢出超过2行省略号 */
    text-overflow: ellipsis;
    overflow: hidden;
}
```

## user-select 属性

``` css
.example {
    user-select: none; /* 禁止选择 */
    user-select: auto; /* 浏览器来决定是否允许选择 */
    user-select: all; /* 可以选择任何内容 */
    user-select: text; /* 只能选择文本 */
    user-select: contain; /* 选择绑定的元素以内的内容 */
}
```
### 两列 左固定右内容垂直居中

方法一：高度无限制

``` html
<div class="box">
    <div class="left">
        <img src="http://fpoimg.com/100x100">
    </div>
    <div class="right">文字</div>
</div>
```

``` css
.box {
    display: -webkit-box; /* 2009年的语法 */
    display: box;
    -webkit-box-align: center;  /* 垂直居中 */
    box-align: center;
    display: -webkit-flex; /* 2012年的语法 */
    display: flex;
    -webkit-align-items: center; /* 垂直居中 */
    align-items: center;
}
.left {
    width: 100px;
    height: 100px;
}
.right {
    -webkit-box-flex: 1;
    box-flex: 1;
    -webkit-flex: 1;
    flex: 1;
}
```

方法二：高度有限制

``` html
<div class="box">
    <div class="left">
        <img src="http://fpoimg.com/100x100">
    </div>
    <div class="right">
        <div class="info">
            <p>文字</p>
            <p>文字</p>
            <p>文字</p>
            <p>文字</p>
            <p>文字</p>
            <p>文字</p>
        </div>
    </div>
</div>
```

``` css
.box {
    position: relative;
}
.left {
    position: absolute;
    top: 0;
    left: 0;
}
.right {
    position: relative;
    margin-left: 100px;
    font-size: 0;
    overflow: hidden;
}
.right:before {
    content: '';
    display: inline-block;
    width: 0;
    min-height: 100px;
    vertical-align: middle;
}
.right .info {
    position: relative;
    display: inline-block;
    vertical-align: middle;
    font-size: 12px;;
}
```

[DEMO1点击这里](http://jsbin.com/nomakudefi/1/edit?html,css,output)
[DEMO2点击这里](http://jsbin.com/gixavidibe/5/edit?html,css,output)

## calc() 允许简单的加、减、乘、除运算

不过存在兼容问题，使用前要了解。

``` html
<ul class="col-3">
    <li></li>
    <li></li>
    <li></li>
</ul>
```

``` css
.col-3 {
    width: 200px;
    height: 200px;
}
.clo-3 li {
    float: left;
    width: calc(100% / 3); /* 33.3% */
    height: 200px;
}
```

## 判断用户手机旋屏

``` css
/* 方法一 */
/* 竖屏 */
@media all and (orientation: portrait) { /* 规定显示设备的取向 */
    .example {
        display: block;
    }
}

/* 横屏 */
@media all and (orientation: landscape) { /* 规定显示设备的取向 */
    .example {
        display: none;
    }
}

/* 方法二 */
/* 横屏 */
@media screen and (min-aspect-ratio: 13/9) { /* 规定显示设备区域的宽度/高度比 */
    .example {
        display: block;
    }
}
```

``` javascript
/* 方法三 */
function checkDirect() {
    // 横屏
    if (window.orientation == 180 || window.orientation == 0) {
        document.querySelector('.example').style.display = 'block'
    }
    // 竖屏
    if (window.orientation == 90 || window.orientation == -90) {
        document.querySelector('.example').style.display = 'none'
    }
}
checkDirect()
window.addEventListener('onorientationchange' in window ? 'orientationchange' : 'resize', checkDirect, false)
```

## 设置 input 标签 placeholder 属性的样式

``` css
.example::-webkit-input-placeholder {
    color: red;
}
```

## 取消点击 a、button、input 标签后区域半透明遮罩

``` css
a, button, input {
    -webkit-tap-highlight-color: rgba(255,0,0,0);
}
```

## 使用 Chrome 模拟手机调试时字体太大

Google Chrome默认浏览器字体最小字体为：12px，而我们手机端页面常常字体小于12px。
**解决：**右上角（自定义及控制） -> 设置 -> 显示高级设置 -> 网络内容（自定义字体） -> 最小字号（最小可以设置为6px）

## 监听 CSS3 动画事件

``` javascript
/* 
动画开始事件：webkitAnimationStart
动画结束事件：webkitAnimationEnd
动画循环事件：webkitAnimationIteration
过渡动画结束事件：webkitTransitionEnd
 */
example.addEventListener('webkitAnimationStart', function() {
    console.log('动画开始') // 动画开始执行一次
}, false)

example.addEventListener('webkitAnimationIteration', function() {
    console.log('动画循环结束') // 动画每循环完成一次执行一次
}, false)
```

## 判断用户是否在手机端

``` javascript
if (/Android|Windows Phone|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)) {
    window.location.href = 'http://www.example.com'
}
```

## 图片水平镜像反转

``` css
/* 方法一 */
.example-1 {
    transform: scaleX(-1);
}

/* 方法二 */
.example-2 {
    transform: rotateY(180deg);
}
```

## 自旋转动画

``` html
<div class="example"></div>
```

``` css
.example {
    position: absolute;
    top: 200px;
    left: 200px;
    width: 100px;
    height: 100px;
    border: 2px solid #000;
    border-radius: 50%;
    animation: autogyRation 4s linear infinite;
}

@keyframes autogyRation {
    from {
        transform: rotate(0deg) translate(-60px) rotate(0deg);
    }
    to {
        transform: rotate(360deg) translate(-60deg) rotate(-360deg);
    }
}
```

[DEMO](http://jsbin.com/guwonokabi/1/edit?html,css,output)

## 扫光动画

``` html
<div class="example">
    <i></i>
</div>
```

``` css
.example {
    position: relative;
    width: 400px;
    height: 200px;
    background: #000;
    overflow: hidden;
}

.example i {
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 100%;
    transform: skewx(-25deg);
    background-image: linear-gradient(
        0deg,
        rgba(255, 255, 255, 0),
        rgba(255, 255, 255, 0.5),
        rgba(255, 255, 255, 0)
    );
}

.example:hover i {
    left: 100%;
    transition: 0.8s;
}
```

[DEMO](http://jsbin.com/xoyukucuwa/1/edit?html,css,output)

## 监测手机晃动事件

``` javascript
// 晃动函数
function init() {
    if (window.DeviceMotionEvent) {
        window.addEventListener('devicemotion', deviceMotionHandler, false)
    } else {
        alert('您的手机不支持晃动事件')
    }
}
init()

// 定义一个摇动的阀值
var SHAKE_THRESHOLD = 1000
// 定义一个变量保存上次更新的时间
var last_update = 0
// 紧接着定义x、y、z记录三个轴的数据以及上一次出发的时间
var x
var y
var z
var last_x
var last_y
var last_z

function deviceMotionHandler(eventData) {
    // 获取含重力的加速度
    var acceleration = eventData.accelerationIncludingGravity

    // 获取当前时间
    var curTime = new Date().getTime()
    var diffTime = curTime - last_update

    // 固定时间段
    if (diffTime > 100) {
        last_update = curTime

        x = acceleration.x
        y = acceleration.y
        z = acceleration.z

        var speed =
            (Math.abs(x + y + z - last_x - last_y - last_z) / diffTime) * 10000

        if (speed > SHAKE_THRESHOLD) {
            // TODO: 在此处可以实现晃动之后所要进行的操作
        }

        last_x = x
        last_y = y
        last_z = z
    }
}
```

## 穿透属性

当元素叠在一起时，需要触发下层的元素时，给上层的元素加该属性。

``` css
.example {
    pointer-event: none;
}
```
## 开启GPU加速方法

> - HTML5 Video
> - transition和animation
> - transform-style: preserve-3d; transform: translate3d(0, 0, 0);
> - transform: translateZ(0px);

## 使:active生效
> - will-change

``` html
<body ontouchstart=""></body>
```

## 禁用自动识别页面中的电话号码

``` html
<meta name="format-detection" content="telephone=no">
```

## 浏览器 UA

```
// iOS微信内置浏览器UA
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 MicroMessenger/6.0.1 NetType/WIFI

// Android微信内置浏览器UA
Mozilla/5.0 (Linux; Android 5.0; SM-N9100 Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36 MicroMessenger/6.0.2.56_r958800.520 NetType/WIFI

// Android内置QQ浏览器UA
Mozilla/5.0 (Linux; Android 5.0; SM-N9100 Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36 V1_AND_SQ_5.3.1_196_YYB_D QQ/5.3.1.2335 NetType/WIFI

// iOS内置QQ浏览器UA
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 QQ/5.2.1.302 NetType/WIFI Mem/28
```

## 取消按钮、输入框、选择框等默认风格

``` css
.example {
    appearance: none
}
```
## 音频事件触发顺序

> canplay -> play -> playing -> canplaythrough -> pause -> suspend -> ended

## Hash 切换体验页面

``` html
<script type="text/html">
    <div class="wrap"></div>
</script>
<script type="text/html">
    <div class="wrap"></div>
</script>
```

``` javascript
var template = document.querySelectorAll('script[type="text/html"]')
var showTemplate = (function() {
    var _fun = function() {
        var hash = location.hash,
            index = parseInt(hash.replace('#', '')) || 0
        document.body.innerHTML = template[index].innerHTML
        if (document.body.childNodes[1].nodeType == 8) {
            document.title = document.body.childNodes[1].nodeValue
        }
    }
    _fun() //自己执行一次
    return _fun
})()
window.addEventListener('hashchange', function() {
    showTemplate()
})
```
## 跑马灯

``` javascript
;(function() {
    var speed = 3000

    var _transitionEnd =
        'onwebkittransitionend' in window
            ? 'webkitTransitionEnd'
            : 'transitionend'

    var DOM_inner = document.querySelector('.comm_top_rolling .rolling_inner'),
        hidedom = null

    DOM_inner.addEventListener(_transitionEnd, swich)

    function move() {
        hidedom = document.querySelector('.comm_top_rolling .rolling_row')
        var moveY = hidedom.getBoundingClientRect().height
        DOM_inner.style.transition = 'transform 0.5s'
        DOM_inner.style.webkitTransition = 'transform 0.5s'
        DOM_inner.style.transform = 'translate3d(0, -' + moveY + 'px, 0)'
        DOM_inner.style.webkitTransform = 'translate3d(0, -' + moveY + 'px, 0)'
    }

    function swich() {
        DOM_inner.style.transition = 'none'
        DOM_inner.style.webkitTransition = 'none'
        DOM_inner.style.transform = 'translate3d(0, 0, 0)'
        DOM_inner.style.webkitTransform = 'translate3d(0, 0, 0)'
        DOM_inner.removeChild(hidedom)
        DOM_inner.appendChild(hidedom)
    }

    setInterval(move, speed)
})()
```
## 插入 DOM 节点

在此前我们常用 `innerHTML`，推荐一个比较冷门但很实用的方法 `insertAdjacentHTML` 和 `insertAdjacentText`

``` javascript
element.insertAdjacentHTML(position, text)
element.insertAdjacentText(position, element)
```

> **beforebegin**
> 在 element 元素的前面。
> **afterbegin**
> 在 element 元素的第一个子节点前面。
> **beforeend**
> 在 element 元素的最后一个子节点后面。
> **afterend**
> 在 element 元素的后面。
